import * as THREE from "three";

export const SCENE_CONFIG = {
  fog: {
    color: new THREE.Color(0x0a2a3a),
    density: 0.005,
  },
  background: {
    color: new THREE.Color(0x0a2a3a),
    texturePath: "/images/background.jpeg",
  },
  camera: {
    fov: 55,
    near: 0.1,
    far: 600,
    position: new THREE.Vector3(-140, 120, 140),
    target: new THREE.Vector3(0, 0, 0),
  },
  octopus: {
    spawn: {
      position: new THREE.Vector3(0, 0, 0),
      clearance: 15,
    },
    animation: {
      speed: 0.4,
    },
  },
  controls: {
    minDistance: 50,
    maxDistance: 200,
    maxPolarAngle: Math.PI,
  },
  lights: {
    ambientColor: new THREE.Color(0x3a2a3a),
    ambientIntensity: 0.4,
    directionalColor: new THREE.Color(0x9fd2e6),
    directionalIntensity: 1.4,
    directionalPosition: new THREE.Vector3(4, 10, 2),
    fillColor: new THREE.Color(0x2a1830),
    fillIntensity: 0.55,
    sunset: {
      color: new THREE.Color(0xff7a3d),
      intensity: 2.6,
      position: new THREE.Vector3(-60, 60, 40),
      rimColor: new THREE.Color(0xff5aa0),
      rimIntensity: 1.1,
      rimPosition: new THREE.Vector3(80, 25, -50),
      groundGlowColor: new THREE.Color(0xffb066),
      groundGlowIntensity: 0.35,
    },
  },
  seabed: {
    size: 80,
    segments: 160,
    color: new THREE.Color(0x9a8a6d),
    heightNoiseScale: 0.18,
    heightAmplitude: 0.6,
  },
  miniWorld: {
    radius: 20,
    segments: 192,
    color: new THREE.Color(0x9a8a6d),
    reliefAmplitude: 2,
    reliefFrequency: 0.08,
    reliefOctaves: 4,
  },
  rocks: {
    count: 150,
    minScale: 0.35,
    maxScale: 2,
    color: new THREE.Color(0x6b6a64),
    buryRatio: 0.35,
  },
  corals: {
    count: 150,
    minScale: 0.6,
    maxScale: 2,
    colors: [
      new THREE.Color(0xff4d9e),
      new THREE.Color(0xff7a4b),
      new THREE.Color(0xb66bff),
      new THREE.Color(0xffd166),
      new THREE.Color(0xe04848),
      new THREE.Color(0xff9ec4),
    ],
  },
  algae: {
    count: 2000,
    minHeight: 0.6,
    maxHeight: 2,
    baseRadius: 0.08,
    tipRadius: 0.025,
    color: new THREE.Color(0x2f8f5e),
    swaySpeed: 1.4,
    swayAmplitude: 0.18,
  },
  particles: {
    count: 1500,
    areaSize: 24,
    height: 12,
    baseSize: 0.05,
    color: new THREE.Color(0xcde8ff),
  },
  fishes: {
    count: 60,
    minRadius: 10,
    maxRadius: 140,
    minY: 6,
    maxY: 90,
    minScale: 2,
    maxScale: 5,
    orientation: {
      yawOffset: Math.PI,
    },
    schooling: {
      ratio: 0.7,
      schoolsCount: 4,
      radius: 10,
      followStrength: 3.5,
      turnSpeed: 6,
    },
    swim: {
      minSpeed: 3,
      maxSpeed: 9,
      wobbleAmp: 0.35,
      wobbleSpeed: 1.2,
    },
  },
  postFx: {
    bloomStrength: 0.35,
    bloomRadius: 0.6,
    bloomThreshold: 0.85,
    exposure: 0.95,
  },
  waterSurface: {
    size: 900,
    segments: 180,
    y: 110,
    deepColor: new THREE.Color(0x0a2a4a),
    shallowColor: new THREE.Color(0xff8a4d),
    causticColor: new THREE.Color(0xffd6a5),
    opacity: 0.85,
    waveAmplitude: 2.4,
    waveFrequency: 0.08,
    waveSpeed: 0.6,
    rippleAmplitude: 0.35,
    rippleFrequency: 0.55,
    rippleSpeed: 2.2,
  },
};
